### ISSUE TITLE
Affixing composer-plugin-api is dangerous

### ISSUE THREAD

**Issue by wjaspers** [tests-always-included/symfony-console-bootstrap-installer#5]
As mentioned by @seldaek with regard to `composer.json`
`composer-plugin-api: "1.0.0"` creates lock-in. if composer is upgraded, this library wont work.
can tolerate any v1.0 version with `composer-plugin-api: "^1.0"`

**Comment by gharcombe-minson** [comment]
I'll get this updated now - I got the email too this morning.
